### ISSUE TITLE
Cannot create a new 3id provider

### ISSUE THREAD

**Issue by Schwartz10** [ceramicstudio/js-3id-did-provider#103] opened 2020-12-10 19:15 UTC
I'm using:

`3id-did-provider@0.1.2`
`@ceramicnetwork/cli@0.16.2`
`@ceramicnetwork/http-client@0.8.7`

These are the only packages I depend on, so versions of any other related packages would be determined by the package.json's of the packages I listed above ^^^.

```js
const ceramic = new Ceramic();
const idWallet = await IdentityWallet.create({
    authId: auth.ID,
    authSecret: auth.secret,
    getPermission: () => Promise.resolve([]),
    ceramic,
});
```
This call throws:
```
(node:52009) UnhandledPromiseRejectionWarning: Error: request timed out
    at Object.fetchJson (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/http-client/src/utils.ts:17:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.applyRecord (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/http-client/src/document.ts:70:23)
    at CeramicClient.applyRecord (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/http-client/src/ceramic-http-client.ts:175:12)
    at TileDoctype.change (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/doctype-tile/src/tile-doctype.ts:48:25)
    at Document.change (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/http-client/src/document.ts:101:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:52009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by oed** [comment] 2020-12-14 09:52
Just replicated this issue. Likely an issue with the ceramic daemon or http-client.

**Comment by oed** [comment] 2020-12-14 10:01
Does this happen every time or just sometimes? I was able to replicate it at first but not anymore. It could potentially be because the schema documents are not available on your node.

**Comment by oed** [comment] 2020-12-14 10:55
Try running the [IDX bootstrap](https://idx.xyz/docs/guide-cli#bootstrap-ceramic-for-idx) command to see if it work better?

**Comment by Schwartz10** [comment] 2020-12-14 18:32
Worked disturbingly fast!

**Comment by Schwartz10** [comment] 2020-12-14 18:59
Ah @oed never mind, this seemed to make it work once, but now it sporadically fails with the same error messages

**Comment by oed** [comment] 2021-01-12 09:45
Are you still having this particular issue @Schwartz10 ?

**Comment by Schwartz10** [comment] 2021-01-14 15:17
Haven't seen this for a while. Will reopen if it reoccurs.

**Comment by Schwartz10** [comment] 2021-01-20 04:34
Hey @oed reopening this, it's happening again with a slightly different message:

`Failed to get block: request timed out`

I'm using all of your latest packages, including the latest ipfs-ceramic docker image.

```
    "3id-did-provider": "^0.4.0",
    "@ceramicnetwork/http-client": "0.9.3",
    "@ceramicstudio/idx": "0.7.0",
    "@ceramicstudio/idx-tools": "0.6.1",
    "@ceramicnetwork/cli": "^0.20.0",
    "@ceramicstudio/idx-cli": "^0.5.0",
```

**Comment by oed** [comment] 2021-01-20 09:36
Looks like some kind of issue with ipfs/js-ceramic. Can you replicate the same issue using only js-ceramic?

**Comment by Schwartz10** [comment] 2021-01-20 12:11
Here's the stack trace, will try without external node
```
at Object.fetchJson (node_modules/@ceramicnetwork/http-client/src/utils.ts:18:15)
      at Function.load (node_modules/@ceramicnetwork/http-client/src/document.ts:87:23)
      at CeramicClient.loadDocument (node_modules/@ceramicnetwork/http-client/src/ceramic-http-client.ts:156:13)```

**Comment by oed** [comment] 2021-01-20 12:12
Do you see any errors in the ceramic daemon?

**Comment by Schwartz10** [comment] 2021-01-20 12:15
NO errors in the daemon (yet), but usually at a certain point I see a bunch of (seemingly recursive or polling) timeout errors there too.

**Comment by Schwartz10** [comment] 2021-01-20 12:30
Eventually the daemon logs:

```
(node:34451) UnhandledPromiseRejectionWarning: TimeoutError: request timed out
    at maybeThrowTimeoutError (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/ipfs-core-utils/src/with-timeout-option.js:42:15)
    at /Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/ipfs-core-utils/src/with-timeout-option.js:96:9
    at async Dispatcher.retrieveCommit (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/core/lib/dispatcher.js:147:24)
    at async Document._fetchLog (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/core/lib/document.js:154:24)
    at async /Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/core/lib/document.js:137:29
    at async run (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/p-queue/dist/index.js:163:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 54)
(node:34451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by migrenaa** [comment] 2021-01-25 21:36
Any updates on that issue? I'm having the same problem. Can update you with more details if needed. (I did run idx bootstrap already).

**Comment by oed** [comment] 2021-01-26 08:24
Hey @migrenaa more details would be very appreciated! Currently I'm unable to reproduce this.

**Comment by migrenaa** [comment] 2021-01-26 16:54
Hi @oed . The problem with me was that I didn't have the latest ceramic cli. I installed it and it works now. 👍

**Comment by oed** [comment] 2021-01-29 13:55
Closing this for now since I believe it should be resolved with the latest Ceramic releases. Reopen or create a new issue if needed @Schwartz10!

**Closed by oed** 2021-01-29 13:55 UTC
Labels: bug
